name: releaser
on:
  release:
    types: 
      - published
      
jobs:
  release-cli-via-krew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Update new version in krew-index
        if: "!github.event.release.prerelease"
        uses: rajatjindal/krew-release-bot@v0.0.38
